# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RVmyLo336F1P7KS4k5FtooOPQP7BxzRX
"""



import pandas as pd
import matplotlib.pyplot as plt
from numpy import sin, exp, pi, linspace
values_func = pd.read_csv("work1.csv", header=None)

def func(x):
  return exp(sin(x))

iks = [0, 0.333333, 0.666667, 1, 1.33333, 1.66667, 2, 2.33333, 2.66667, 3, 3.33333, 3.66667, 4, 4.33333, 4.66667, 5, 5.33333, 5.66667, 6, 6.33333, 6.66667, 7, 7.33333, 7.66667, 8, 8.33333, 8.66667, 9, 9.33333, 9.66667, 10]
igrek = [1, 1.38707, 1.8559, 2.31978, 2.64306, 2.70583, 2.48258, 2.06078, 1.57976, 1.15156, 0.826489, 0.605757, 0.469164, 0.394943, 0.368264, 0.383305, 0.443379, 0.560908, 0.756226, 1.0514, 1.45376, 1.92897, 2.38094, 2.67115, 2.68951, 2.42855, 1.98884, 1.51001, 1.09562, 0.786992, 0.58041]
X, Y = values_func[0], values_func[1]

t = linspace(0, 10, 31)
f = [func(x) for x in t]
plt.plot(t, f)
plt.plot(X, Y)
plt.scatter(iks, igrek)
plt.legend(["Истинная функция", "Интерполяция"])

import pandas as pd
import matplotlib.pyplot as plt
from numpy import sin, exp, pi, linspace
values_func1 = pd.read_csv("work2.csv", header=None)

def func(x):
  return exp(sin(x))

iks = [9.99358, 9.94234, 9.84039, 9.68876, 9.48902, 9.24322, 8.95388, 8.62396, 8.25686, 7.85634, 7.42651, 6.97178, 6.49682, 6.00649, 5.50584, 5, 4.49416, 3.99351, 3.50318, 3.02822, 2.57349, 2.14366, 1.74314, 1.37604, 1.04612, 0.756779, 0.510977, 0.311239, 0.159614, 0.0576584, 0.00641746]
igrek = [0.58355, 0.609714, 0.667814, 0.770337, 0.937817, 1.19789, 1.57411, 2.05017, 2.50913, 2.71827, 2.48436, 1.88788, 1.23616, 0.760959, 0.495896, 0.383305, 0.376709, 0.471167, 0.702041, 1.11978, 1.71264, 2.31718, 2.67831, 2.66737, 2.37616, 1.98691, 1.63073, 1.35831, 1.17226, 1.05932, 1.00644]
X, Y = values_func1[0], values_func1[1]

t = linspace(0, 10, 31)
f = [func(x) for x in t]
plt.plot(t, f)
plt.plot(X, Y)
plt.scatter(iks, igrek)
plt.legend(["Истинная функция", "Интерполяция"])